version: '{build}'
image: Visual Studio 2017 Preview
clone_depth: 1
init:
- cmd: git config --global core.autocrlf true
install:
- ps: Install-Product node ''
- choco install gitversion.portable -pre -y
cache:
 - "%LOCALAPPDATA%\\Yarn"
 before_build:  
  - ps: gitversion /l console /output buildserver
build_script:
- cmd: >-
    dotnet --version

    dotnet restore ./CryptoManager/CryptoManager.csproj --verbosity m

    cd ./CryptoManager

    node -v

    yarn -v

    yarn

    REM dotnet build ./CryptoManager.csproj --verbosity m

    dotnet publish --runtime win10-x64
test: off