version: 1.2.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017 Preview
clone_depth: 1
init:
- cmd: git config --global core.autocrlf true
install:
- ps: Install-Product node ''
cache:
 - "%LOCALAPPDATA%\\Yarn" 
build_script:
- cmd: >-
    dotnet --version

    dotnet restore ./CryptoManager/CryptoManager.csproj --verbosity m

    cd ./CryptoManager

    node -v

    yarn -v

    yarn

    REM dotnet build ./CryptoManager.csproj --verbosity m

    dotnet publish --runtime win10-x64

    cd ..

    7z a CryptoManager-win64.zip docs\RunScripts\RunWindows.bat

    7z a CryptoManager-win64.zip CryptoManager\bin\Debug\netcoreapp2.0\win10-x64\publish
test: off
artifacts:
- path: 'CryptoManager-win64.zip'
  name: CryptoManager-win64
deploy:
- provider: Environment
  name: CryptoManager