// <auto-generated />
using CryptoManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Model.Enums;
using System;

namespace Model.Migrations
{
    [DbContext(typeof(CryptoContext))]
    [Migration("20171214211820_TransactionDetailAndExchange")]
    partial class TransactionDetailAndExchange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Model.DbModels.CryptoTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("BuyAmount");

                    b.Property<string>("BuyCurrency");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("DateTime");

                    b.Property<Guid?>("ExchangeId");

                    b.Property<decimal>("FeeAmount");

                    b.Property<string>("FeeCurrency");

                    b.Property<decimal>("InAmount");

                    b.Property<string>("InCurrency");

                    b.Property<decimal>("OutAmount");

                    b.Property<string>("OutCurrency");

                    b.Property<decimal>("SellAmount");

                    b.Property<string>("SellCurrency");

                    b.Property<string>("TransactionKey");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Model.DbModels.Exchange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("PrivateKey");

                    b.Property<string>("PublicKey");

                    b.Property<bool>("SupportsPrivateKey");

                    b.Property<bool>("SupportsPublicKey");

                    b.HasKey("Id");

                    b.ToTable("Exchange");
                });

            modelBuilder.Entity("Model.DbModels.Setting", b =>
                {
                    b.Property<int>("Key");

                    b.Property<string>("Value");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Model.DbModels.CryptoTransaction", b =>
                {
                    b.HasOne("Model.DbModels.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId");
                });
#pragma warning restore 612, 618
        }
    }
}
