// <auto-generated />
using CryptoManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Model.Enums;
using System;

namespace Model.Migrations
{
    [DbContext(typeof(CryptoContext))]
    partial class CryptoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Model.DbModels.CryptoTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("BuyAmount");

                    b.Property<string>("BuyCurrency");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("DateTime");

                    b.Property<Guid>("ExchangeId");

                    b.Property<decimal>("FeeAmount");

                    b.Property<string>("FeeCurrency");

                    b.Property<string>("InAdress");

                    b.Property<decimal>("InAmount");

                    b.Property<string>("InCurrency");

                    b.Property<string>("OutAdress");

                    b.Property<decimal>("OutAmount");

                    b.Property<string>("OutCurrency");

                    b.Property<decimal>("SellAmount");

                    b.Property<string>("SellCurrency");

                    b.Property<string>("TransactionKey");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Model.DbModels.Setting", b =>
                {
                    b.Property<int>("Key");

                    b.Property<string>("Value");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
